import { AnalyticsData } from '../types/analytics.types';

export const analyticsData: AnalyticsData = {
  metrics: [
    {
      id: '1',
      label: 'Total Income',
      value: 4870.34,
      color: '#4f46e5',
      icon: 'BanknoteArrowUp',
    },
    {
      id: '2',
      label: 'Total Saving',
      value: 147.69,
      color: '#10b981',
      icon: 'PiggyBank',
    },
    {
      id: '3',
      label: 'Total Expenses',
      value: 354,
      color: '#f59e0b',
      icon: 'BanknoteArrowDown',
    },
    {
      id: '4',
      label: 'Categories',
      value: 40,
      color: '#ef4444',
      icon: 'Component',
    },
  ],
  
  expenseCategories: [
    { id: '1', name: 'Food', amount: 1200, percentage: 38, color: '#ef4444' },
    {
      id: '2',
      name: 'Transport',
      amount: 1200,
      percentage: 38,
      color: '#3b82f6',
    },
    {
      id: '3',
      name: 'Healthcare',
      amount: 1200,
      percentage: 38,
      color: '#10b981',
    },
    {
      id: '4',
      name: 'Education',
      amount: 1200,
      percentage: 38,
      color: '#f59e0b',
    },
    {
      id: '5',
      name: 'Clothes',
      amount: 1200,
      percentage: 38,
      color: '#8b5cf6',
    },
    { id: '6', name: 'Pets', amount: 1200, percentage: 38, color: '#ec4899' },
    {
      id: '7',
      name: 'Entertainment',
      amount: 1200,
      percentage: 38,
      color: '#06b6d4',
    },
  ],

  monthlyExpenses: [
    { month: 'Jan', income: 4200, expense: 3800, saving: 250 },
    { month: 'Feb', income: 3800, expense: 4200, saving: 560 },
    { month: 'Mar', income: 5200, expense: 3600, saving: 240 },
    { month: 'Apr', income: 3600, expense: 4800, saving: 450 },
    { month: 'May', income: 4800, expense: 4200, saving: 2550 },
    { month: 'Jun', income: 3200, expense: 3800, saving: 220 },
    { month: 'Jul', income: 4600, expense: 4400, saving: 550 },
    { month: 'Aug', income: 4400, expense: 3800, saving: 350 },
    { month: 'Sep', income: 5000, expense: 4600, saving: 667 },
    { month: 'Oct', income: 4000, expense: 4200, saving: 364 },
    { month: 'Nov', income: 4200, expense: 3600, saving: 895 },
    { month: 'Dec', income: 4800, expense: 4000, saving: 524 },
  ],
  transactions: [
    {
      id: '1',
      type: 'income',
      category: 'Donation',
      date: '01.10.2024',
      description: 'Miami Public House',
      amount: 92.0,
      currency: 'USD',
      icon: 'BanknoteArrowUp',
      color: '#10b981',
    },
    {
      id: '2',
      type: 'expense',
      category: 'Utilities',
      date: '01.10.2024',
      description: 'Monthly Grocery',
      amount: -43.0,
      currency: 'USD',
      icon: 'UtilityPole',
      color: '#3b82f6',
    },
    {
      id: '3',
      type: 'expense',
      category: 'Transportation',
      date: '01.10.2024',
      description: 'Uber Ride',
      amount: -12.5,
      currency: 'USD',
      icon: 'Car',
      color: '#f59e0b',
    },
    {
      id: '4',
      type: 'expense',
      category: 'Dining',
      date: '02.10.2024',
      description: 'Cheesecake Factory',
      amount: -67.23,
      currency: 'USD',
      icon: 'HandPlatter',
      color: '#8b5cf6',
    },
    {
      id: '5',
      type: 'income',
      category: 'Shopping',
      date: '02.10.2024',
      description: 'Amazon.com',
      amount: -145.99,
      currency: 'USD',
      icon: 'ShoppingCart',
      color: '#ec4899',
    },
  ],
};
