import { WalletData } from '../types/wallet.types';

export const walletData: WalletData = {
  accounts: [
    {
      id: '1',
      type: 'savings',
      name: 'Savings Account',
      balance: 90583,
      icon: 'piggy-bank',
      color: '#4f46e5',
    },
    {
      id: '2',
      type: 'checking',
      name: 'Credit Card',
      balance: 25000,
      icon: 'credit-card',
      color: '#8b5cf6',
    },
    {
      id: '3',
      type: 'investment',
      name: 'Investment Portfolio',
      balance: 150000,
      icon: 'trending-up',
      color: '#ec4899',
    },
    {
      id: '4',
      type: 'emergency',
      name: 'Emergency Fund',
      balance: 85932,
      icon: 'shield',
      color: '#06b6d4',
    },
  ],

  creditCards: [
    {
      id: '1',
      name: 'Premium Checking Account',
      cardNumber: '**** **** **** 7890',
      balance: 87549.32,
      limit: 100000,
      expiryDate: '12/26',
      cardholderName: 'Emily Johnson',
      isVisa: true,
      meta: [
        {
          id: '1',
          title: 'Available Balance',
          amount: 432668,
          change: 10.5,
          changePercentage: 2.5,
        },
        {
          id: '2',
          title: "This Month's Spending",
          amount: 245860,
          change: -5.2,
          changePercentage: -2.1,
        },
      ],
    },
    {
      id: '2',
      name: 'Premium Checking Account',
      cardNumber: '**** **** **** 1234',
      balance: 65432.1,
      limit: 85000,
      expiryDate: '09/25',
      cardholderName: 'John Smith',
      isVisa: false,
      meta: [
        {
          id: '1',
          title: 'Total Period Expenses',
          amount: 2530,
          change: 3.8,
          changePercentage: 1.5,
        },
        {
          id: '2',
          title: 'Total Period Income',
          amount: 24560,
          change: 12.3,
          changePercentage: 5.2,
        },
      ],
    },
    {
      id: '3',
      name: 'Investment Portfolio',
      cardNumber: '**** **** **** 1234',
      balance: 15000,
      limit: 85000,
      expiryDate: '09/25',
      cardholderName: 'John Smith',
      isVisa: false,
      meta: [
        {
          id: '3',
          title: 'Total Contribution',
          amount: 2530,
          change: 3.8,
          changePercentage: 1.5,
        },
        {
          id: '4',
          title: 'Quarterly Performance',
          amount: '+6.8%',
          change: 12.3,
          changePercentage: 5.2,
        },
      ],
    },
    {
      id: '4',
      name: 'Emergency Fund',
      cardNumber: '**** **** **** 1234',
      balance: 25000,
      limit: 85000,
      expiryDate: '09/25',
      cardholderName: 'John Smith',
      isVisa: false,
      meta: [
        {
          id: '3',
          title: 'Months of Expenses Covered',
          amount: '6 Months',
          change: 3.8,
          changePercentage: 1.5,
        },
        {
          id: '4',
          title: 'Interest Earned (YTD)',
          amount: 24560,
          change: 12.3,
          changePercentage: 5.2,
        },
      ],
    },
  ],

  transactions: [
    {
      id: '1',
      type: 'income',
      category: 'Donation',
      date: '01.10.2024',
      description: 'Miami Public House',
      amount: 92.0,
      currency: 'USD',
      icon: 'arrow-down',
      color: '#10b981',
    },
    {
      id: '2',
      type: 'expense',
      category: 'Utilities',
      date: '01.10.2024',
      description: 'Monthly Grocery',
      amount: -43.0,
      currency: 'USD',
      icon: 'arrow-up',
      color: '#3b82f6',
    },
    {
      id: '3',
      type: 'expense',
      category: 'Transportation',
      date: '01.10.2024',
      description: 'Uber Ride',
      amount: -12.5,
      currency: 'USD',
      icon: 'car',
      color: '#f59e0b',
    },
    {
      id: '4',
      type: 'expense',
      category: 'Dining',
      date: '02.10.2024',
      description: 'Cheesecake Factory',
      amount: -67.23,
      currency: 'USD',
      icon: 'utensils',
      color: '#8b5cf6',
    },
    {
      id: '5',
      type: 'income',
      category: 'Shopping',
      date: '02.10.2024',
      description: 'Amazon.com',
      amount: -145.99,
      currency: 'USD',
      icon: 'shopping-bag',
      color: '#ec4899',
    },
  ],
};
